# Train and deploy a model on Cloud

## Train model
Create a model to predict rent price of appartment based on features

- surface
- number of rooms
- levels
- garden and/or garage

## Create a Cloud structure

## Push for deployment

In [1]:
import pyforest
from sklearn.linear_model import LinearRegression

In [2]:
print(f"Library sklearn version {sklearn.__version__}")

<IPython.core.display.Javascript object>

Library sklearn version 0.24.1


In [2]:
# load dataset
df = pd.read_csv('data/MOCK_DATA.csv')
df.shape

<IPython.core.display.Javascript object>

(1000, 7)

In [3]:
df.head()

id  surface  level  room  garden  garage  price_rent
0   1      153      1     2       0       1        2111
1   2      162      1     3       1       1        1684
2   3      163      3     3       0       0        1857
3   4       73      1     2       1       1        2756
4   5       94      3     1       1       0        1361

In [4]:
# define X, y
X = df.drop(['id','price_rent'], axis=1).values
y = df.price_rent.values

In [5]:
X[:985], X[-15:]

(array([[153,   1,   2,   0,   1],
        [162,   1,   3,   1,   1],
        [163,   3,   3,   0,   0],
        ...,
        [145,   2,   4,   0,   1],
        [ 89,   3,   1,   0,   1],
        [167,   1,   4,   0,   1]]),
 array([[134,   1,   3,   0,   1],
        [124,   3,   2,   0,   1],
        [243,   1,   1,   1,   1],
        [122,   2,   3,   0,   1],
        [199,   2,   3,   0,   0],
        [176,   1,   3,   1,   0],
        [ 91,   1,   1,   0,   1],
        [ 84,   1,   1,   1,   0],
        [131,   2,   4,   0,   1],
        [159,   1,   4,   0,   1],
        [223,   2,   3,   1,   1],
        [237,   2,   4,   1,   1],
        [161,   3,   3,   1,   0],
        [129,   2,   2,   0,   1],
        [166,   1,   2,   1,   1]]))

In [6]:
# create a classifier
clf = LinearRegression()

In [7]:
clf.fit(X[:985],y[:985]).predict(X[-15:])

array([2023.39986858, 1952.09161181, 2048.40321177, 1978.3317618 ,
       2035.16745143, 2049.17984613, 2049.7917903 , 2067.79802697,
       1963.15270378, 2010.75917493, 1968.85214685, 1954.4663277 ,
       1960.47146252, 1996.04918419, 2019.58044527])

In [8]:
clf.score(X[-15:],y[-15:])

-0.14452567030019337

In [9]:
# save model for futur deployement
model_file_path = 'rent_price_predictor.pkl'

import pickle

# save the model to disk
pickle.dump(clf, open(model_file_path, 'wb'))

In [10]:
row_one = np.array([131,   2,   4,   0,   1]).reshape(1,-1)
model = pickle.load(open(model_file_path, 'rb'))
model.predict(row_one)

<IPython.core.display.Javascript object>

array([1963.15270378])

In [11]:
#pip install flask
